// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAon4ogLBMlZVXbWJSJ0D033pATmdJkyng',
    appId: '1:290300541087:web:ef9c443cd722da8b408aaa',
    messagingSenderId: '290300541087',
    projectId: 'dreamst-84fca',
    authDomain: 'dreamst-84fca.firebaseapp.com',
    storageBucket: 'dreamst-84fca.appspot.com',
    measurementId: 'G-PXHRKJZEFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLpU06TsPTF8vsCDpo2wqbmvkUTAM-I_Y',
    appId: '1:290300541087:android:55c7b05acc2d87ae408aaa',
    messagingSenderId: '290300541087',
    projectId: 'dreamst-84fca',
    storageBucket: 'dreamst-84fca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUZz1ZGGpyVo7WFl_HnUz357r7j635AU',
    appId: '1:290300541087:ios:b7c3bdda6865169b408aaa',
    messagingSenderId: '290300541087',
    projectId: 'dreamst-84fca',
    storageBucket: 'dreamst-84fca.appspot.com',
    iosBundleId: 'com.example.dreamst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIUZz1ZGGpyVo7WFl_HnUz357r7j635AU',
    appId: '1:290300541087:ios:b9ef2e204ae0c917408aaa',
    messagingSenderId: '290300541087',
    projectId: 'dreamst-84fca',
    storageBucket: 'dreamst-84fca.appspot.com',
    iosBundleId: 'com.example.dreamst.RunnerTests',
  );
}
